POST http://localhost:3333/trips
Content-Type:application/json

{
  "destination": "Brazil",
  "starts_at": "2024-11-05 18:00:00",
  "ends_at": "2024-11-05 18:00:00",
  "owner_name": "Rafael Neves",
  "owner_email": "rafael@gmail.com",
  "emails_to_invite": ["abc@gmail.com", "abc@gmail.com"]
}

###

GET http://localhost:3333/trips/605cca62-b919-4bb3-9038-336cd93a4bb3/confirm