// Create activity
POST http://localhost:3333/trips/06864770-69de-42f0-97b6-a8bb6582c0de/activities
Content-Type: application/json

{
  "title": "New activity",
  "occurs_at": "2024-11-08 18:00:00"
}

### 
// Get activities
GET http://localhost:3333/trips/06864770-69de-42f0-97b6-a8bb6582c0de/activities

###
// Create link
POST http://localhost:3333/trips/06864770-69de-42f0-97b6-a8bb6582c0de/links
Content-Type: application/json

{
  "title": "Almoço",
  "url": "https://google.com.br"
}

###
// Get links
GET http://localhost:3333/trips/06864770-69de-42f0-97b6-a8bb6582c0de/links

###
// Create trip
POST http://localhost:3333/trips
Content-Type:application/json

{
  "destination": "Brazil",
  "starts_at": "2024-11-05 18:00:00",
  "ends_at": "2024-11-05 18:00:00",
  "owner_name": "Rafael Neves",
  "owner_email": "rafael@gmail.com",
  "emails_to_invite": ["abc@gmail.com", "abc@gmail.com"]
}

###
// Get Trip
GET http://localhost:3333/trips/605cca62-b919-4bb3-9038-336cd93a4bb3/confirm

###
// Get Participants
GET http://localhost:3333/trips/3411caac-1578-40b5-b7fa-8c1ca7f882ee/participants

###
// Get Participants confirmed in trip
GET http://localhost:3333/participants/0456dc12-90ad-4ecf-b8dc-214819145732/confirm

###
// Create Invite
POST http://localhost:3333/trips/3411caac-1578-40b5-b7fa-8c1ca7f882ee/invites
Content-Type: application/json

{
  "email": "123@gmail.com"
}